### ISSUE TITLE
Partir a função `scrape_data` em funções menores.

### ISSUE THREAD

**Issue by raissonsouto** [raissonsouto/pijama2json#1]
A função `scrape_data` tem como objetivo receber o PDF convertido em uma lista de strings, onde cada string representa uma linha do texto contido no PDF. Nesse processo, ela itera por cada linha para extrair as informações de cada disciplina, resultando em uma lista de JSONs. Cada JSON contém as informações relevantes de uma disciplina específica.

Entretanto, essa função tornou-se extensa, contendo números mágicos e outros problemas de legibilidade. Para resolver isso, sugere-se refatorar o código, dividindo a função em várias partes menores. Cada uma dessas partes será responsável por resolver tarefas mais específicas, como identificar o nome da disciplina, obter o nome do(s) professor(es) e assim por diante. Essa abordagem tornará o código mais organizado e mais fácil de entender.

**Comment by ghost** [comment]
Hi I would like to try and fix this issue. could you please assign it to me?

**Comment by raissonsouto** [comment]
Absolutely! I'd be glad to have your assistance!

**Comment by raissonsouto** [comment]
Done: https://github.com/raissonsouto/pijama2json/pull/7
